services:                                                          
    db:                                                               
      image: postgres:16-alpine
      environment:                                                    
        POSTGRES_USER: AkihabaraNin                                        
        POSTGRES_PASSWORD: AirbusA3501041                               
        POSTGRES_DB: brokecode                                              
      ports: ["5432:5432"]                                             
      volumes: ["pgdata:/var/lib/postgresql/data"]                     
volumes:                                                            
  pgdata: